{% set name = "mopac" %}
{% set version = "23.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openmopac/mopac/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b4c3959c36706ae06601819c5e057a261f2265d196986dd0c38ab63990dd17cd

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ stdlib("c") }}    # [unix]
    - {{ compiler('fortran') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - cmake
    - ninja
    - python
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - mdi
  host:
    - libblas
    - liblapack
    - mdi

test:
  commands:
    - test -f $PREFIX/lib/lib{{ name }}$SHLIB_EXT  # [unix]
    - if not exist %LIBRARY_BIN%\\libmopac.dll exit 1  # [win]
    - test -f $PREFIX/bin/{{ name }}-makpol  # [unix]
    - test -f $PREFIX/bin/{{ name }}-param  # [unix]
    - {{ name }} --version

about:
  home: http://openmopac.net
  dev_url: https://github.com/openmopac/mopac
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
  summary: The modern open-source version of the Molecular Orbital PACkage (MOPAC)

extra:
  recipe-maintainers:
    - awvwgk
    - godotalgorithm
